#!/bin/bash

while getopts "na:rb:e:h" o; do
    case "${o}" in 
	
	n)
	    if [ -d ~/.ja ]; then
		echo "Esteu segurs que voleu borrar la base de dades? [s/n]"
		read RESPOSTA
		[ RESPOSTA='s' ] && rm -f ~/.ja/*
	    else
	    	mkdir ~/.ja
	    fi
 	    ;;
	
	a)
	    
	    if [ -f ~/.ja/$OPTARG ]; then
		echo "Aquet nom de projecte ja existeix"
	    else
		touch ~/.ja/$OPTARG
	    fi
	    ;;
    esac
done


