#!/bin/bash

while getopts "na:rb:e:h" o; do
    case "${o}" in 
	
	n)
	    if [ -d ~/.ja ]; then
		echo "Esteu segurs que voleu borrar la base de dades? [s/n]"
		read RESPOSTA
		[ RESPOSTA='s' ] && rm -f ~/.ja/*
	    else
	    	mkdir ~/.ja
	    fi
 	    ;;
	
	a)
	    
	    if [ -f ~/.ja/$OPTARG ]; then
		echo "Aquet nom de projecte ja existeix"
	    else
		touch ~/.ja/$OPTARG
	    fi
	    ;;
	r)

	    if [ -f ~/.ja/$OPTARG ]; then
		rm ~/.ja/$OPTARG	
	    else
		echo "Aquet nom de projecte no existeix"
	    fi
	    ;;
	
	b)
	    if [ -f ~/.ja/$OPTARG ]; then
		LINE=$(tail -1 ~/.ja/$OPTARG | cut -d " " -f  1-1)
		if [ "$LINE" = "B" ]; then 
		    echo "S'esta treballant amb el projecte"
		else
		    echo -n "B  " >> ~/.ja/$OPTARG
		    date +%s >> ~/.ja/$OPTARG
		fi
	    else
		echo "Aquet projecte no existeix"
	    fi
	    ;;
		
	e)
	    if [ -f ~/.ja/$OPTARG ]; then
		LINE=$(tail -1 ~/.ja/$OPTARG | cut -d " " -f  1-1)
		if [ "$LINE" = "E" ]; then 
		    echo "No s'esta treballant amb el projecte"
		else
		    echo -n "E  " >> ~/.ja/$OPTARG
		    date +%s >> ~/.ja/$OPTARG
		fi
	    else
		echo "Aquet projecte no existeix"
	    fi	    
	    ;;
    

	h)
	
	    echo -e "\nAquesta es una commanda d'ajuda:\n"\
			 "L'opcio -n crea una carpeta de projecta nova, en cas de que ja existeixi borra el contingut de dintre.\n" \
		"L'opcio -a crea un projecte nou de com <prjid> , la commanda sera: ./ja -a <prjid>\n" \
		"L'opcio -r esborra un projecte de nom <prjid>\n" \
		"L'opcio -b indica que es vol començar a treballar amb el projecte <prjid>, la commanda sera: ./ja -b <prjid>\n" \
		"L'opcio -e indica que es vol acabar de treballar amb el projecte <prjid>, la commanda sera: ./ja -e <prjid>\n" \
		"Finalment , si no fiquem cap opcio i nomes el nom d'un projecte <prjid>, s'ens mostrara una resum del projecte <prjid>"\
			 "en el que veurem el total de segons i en quants lots de treball ho hem fet.\n"
	    
	    
	    ;;
	
    esac
done

#Sergi ja

# http://unix.stackexchange.com/questions/50563/how-can-i-detect-that-no-options-were-passed-with-getopts
if [ $OPTIND -eq 1 ]; then
    NUMERO=$(grep -c "E" ~/.ja/$1)
    echo El numero de lots de treball es de $NUMERO
    awk '/^B/{s=$2} /^E/{t=t+$2-s} END {printf "El temps total dedicat es de %.0f segons\n", t}' ~/.ja/$1
    #Agafem les linies que començen per B i guardem el valor del temps     
    #Agafem les linies que començen per E i summem el valor del temps a t (inicialment 0) i hi restem el valor del temps de B (s)
fi
